echo "***************************Start detecting and evaluating*******************"
echo "Here is total folder. "
echo "It will start to run collect.py first and then run ARC_evaluate.py. "
echo "The first terminal is connect the BLE4.0 and check the connection. "
echo "The second terminal is to evaluate the sound and tell us COPD or normal. "
echo "****************************************************************************"
gnome-terminal -x bash -c "echo 1234 | sudo -S python ./Visualize_evaluate/collect.py"
gnome-terminal -x bash -c "python ./model/ARC_evaluate.py"